name: Disposable Windows SSH
name: Disposable Windows SSH
on:
  workflow_dispatch:

jobs:
  windows-runner:
    runs-on: windows-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Launch SSH Session (Upterm)
        uses: lhotari/action-upterm@v1
        with:
          # Automatically pulls your registered SSH keys from github.com/dkappe.keys
          # and denies access to anyone else
          limit-access-to-actor: true
          wait-timeout-minutes: 360 # Keeps runner alive up to 6 hours
